version: '3.5'


services:
  tacobell-delivery-api:
    container_name: tacobell-delivery-api
    build: .
    ports:
      - "1337:1337"
    volumes:
      - .:/src/app

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tacobell-delivery-api